### ISSUE TITLE
竞拍出价过程

### ISSUE THREAD

**Issue by EilianLiu** [TopBidder/v2-bug-bounty#33]
竞拍过程我直接按照当前提示价格进行了竞拍，并授权了交易，之后我担心这个价格不够，又进行了自定义价格交易，以更高的价格进行了出价，最后成交价格是我第一次出的价格

0x98d6e05Ac0FEE4818c81E9f11a7B5149Ef1b270A

**Comment by TopBidder** [comment]
可以超额出价是产品机制
