### ISSUE TITLE
申请艺术家 厂牌 错别字

### ISSUE THREAD

**Issue by EilianLiu** [TopBidder/v2-bug-bounty#36]
<img width="685" alt="image" src="https://user-images.githubusercontent.com/40413863/161363329-415ed92e-1fe0-46eb-ba1a-5637d05c63d4.png">
<img width="456" alt="image" src="https://user-images.githubusercontent.com/40413863/161363342-39df8bcc-fa72-48cf-952f-d61d18c52701.png">

应该是错别字吧

0x98d6e05Ac0FEE4818c81E9f11a7B5149Ef1b270A

**Comment by TopBidder** [comment]
Tweet是Twitter一条推文的英文
